### ISSUE TITLE
FeedAHelp: Implement i18n Localization for language translation

### ISSUE THREAD

**Issue by TanvirAlam** [FeedAHelp/FeedAHelpless#270]
implement multilingual support for your app, this tutorial will guide you through all of the Next.js internationalization (i18n) essentials

Source: https://phrase.com/blog/posts/nextjs-i18n/

https://nextjs.org/docs/pages/building-your-application/routing/internationalization

Since v10, Next.js has had built-in support for internationalized routing. With this addition, given some locale configuration, Next.js automatically handles localized routing. Included out of the box in Next.js are sub-path and domain routing. Sub-path routing is where the locale is part of the URL, like /blog, /fr/blog, /es/blog. Domain routing has the locale appear in the top-level domain, like mywebsite.com/blog, mywebsite.fr/blog, mywebsite.nl/blog. Of course, we will need to configure the i18n in our app for these routes to work. Let’s see this in practice by building a small demo app.

```
[i18next](https://www.i18next.com/) (22.0.4)
[react-i18next](https://react.i18next.com/) (12.0.0)
[next-i18next](https://github.com/i18next/next-i18next) (12.0.1)
```

![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/3250040/2750557b-39dd-4eaa-b1bd-eadbb40248b7)

**Comment by sojib-mondol** [comment]
Thank you for giving the resources.

**Comment by sojib-mondol** [comment]
In this ticket, I thy to implement the i18n localization for language translation. But not properly understanding how can I do it. I watched some of the youtube videos but did not really get it. One video is really interesting to me you can also watch https://www.youtube.com/watch?v=H9O9HdKNytc&t=4s 

And in our projects I have faced issue to pnpm i next-i18next, it is not installing. And I am leaving this ticket because I think I can not able to finish it. But If someone wants to do it I would love to collaborate with him. Thanks.
